package agent

import (
	"context"
	"testing"

	"orchestra/agent/internal/llm"
	"orchestra/agent/internal/tools"
)

// Some server tools run code on the provider's side — the current web_search
// filters its results that way — and that execution lives in a container the
// conversation must name again on every later turn. Without it the provider
// refuses to continue, which killed a run after the work was already done:
//
//	container_id is required when there are pending tool uses generated by
//	code execution with tools
//
// Nothing here is a capability we grant. The container is the provider's, on
// the provider's machines, holding only what this conversation already sent.

func withContainer(id, text, stop string) *llm.Response {
	r := textResp(text, 10, stop)
	r.Container = &llm.Container{ID: id}
	return r
}

func TestAContainerIsCarriedToTheNextTurn(t *testing.T) {
	prov := &fakeProvider{}
	prov.fn = func(i int, _ llm.Request) *llm.Response {
		if i == 0 {
			return withContainer("cnt_abc", "searching", "tool_use")
		}
		return textResp("done", 10, "end_turn")
	}
	r := NewRunner(Config{Task: "TASK", Provider: prov, Tools: tools.New(t.TempDir()), MaxIter: 5})
	if err := r.Run(context.Background()); err != nil {
		t.Fatal(err)
	}

	if len(prov.reqs) < 2 {
		t.Fatalf("only %d requests", len(prov.reqs))
	}
	if prov.reqs[0].Container != "" {
		t.Errorf("first request named a container it could not know about: %q", prov.reqs[0].Container)
	}
	if prov.reqs[1].Container != "cnt_abc" {
		t.Errorf("second request carried %q, want the container the first turn created", prov.reqs[1].Container)
	}
}

// The provider reports the container on the turns that use it; the id still
// has to ride along on the turns in between.
func TestTheContainerPersistsAcrossTurnsThatDoNotReportOne(t *testing.T) {
	prov := &fakeProvider{}
	prov.fn = func(i int, _ llm.Request) *llm.Response {
		switch i {
		case 0:
			return withContainer("cnt_abc", "searching", "tool_use")
		case 1:
			return textResp("thinking", 10, "tool_use") // no container reported
		default:
			return textResp("done", 10, "end_turn")
		}
	}
	r := NewRunner(Config{Task: "TASK", Provider: prov, Tools: tools.New(t.TempDir()), MaxIter: 5})
	r.Run(context.Background())

	if len(prov.reqs) < 3 {
		t.Fatalf("only %d requests", len(prov.reqs))
	}
	if prov.reqs[2].Container != "cnt_abc" {
		t.Errorf("third request carried %q; a turn that reported no container must not drop it", prov.reqs[2].Container)
	}
}

// A conversation that never ran code on the provider's side sends nothing —
// the field is omitted rather than sent empty.
func TestNoContainerIsSentWhenNoneWasCreated(t *testing.T) {
	prov := &fakeProvider{}
	prov.fn = func(i int, _ llm.Request) *llm.Response {
		if i == 0 {
			return textResp("working", 10, "tool_use")
		}
		return textResp("done", 10, "end_turn")
	}
	r := NewRunner(Config{Task: "TASK", Provider: prov, Tools: tools.New(t.TempDir()), MaxIter: 5})
	r.Run(context.Background())

	for i, req := range prov.reqs {
		if req.Container != "" {
			t.Errorf("request %d named container %q with none in play", i, req.Container)
		}
	}
}

// A response with no container at all must not panic the accessor — the common
// case is every turn of every conversation that uses no server tools.
func TestContainerIDOnAResponseWithout(t *testing.T) {
	if got := (&llm.Response{}).ContainerID(); got != "" {
		t.Errorf("ContainerID() = %q on a response with no container", got)
	}
	var nilResp *llm.Response
	if got := nilResp.ContainerID(); got != "" {
		t.Errorf("ContainerID() = %q on a nil response", got)
	}
}
